Create TABLE IF NOT EXISTS projects(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> '') ,
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

Create TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <>''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);


INSERT INTO projects (name, priority, description, deliverydate)
VALUES ('Make a Web App', 1, 'Using JavaScript', '2019-05-12');

INSERT INTO tasks(name, done, projectId)
VALUES('dasfadf',false, 1);